version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: com.google.android.gms:play-services-maps
    versions:
    - 17.0.0
